# Generated by Django 3.2.7 on 2021-11-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_extend_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_profile_picture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
